apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vortex.fullname" . }}-secrets
  labels:
    {{- include "vortex.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioSecretKey | quote }}