apiVersion: v1
kind: Secret
metadata:
  name: vortex-secrets
  namespace: vortex
type: Opaque
stringData:
  DATABASE_URL: "postgres://vortex:vortex_secret_password@host.minikube.internal:5432/vortex_db?sslmode=disable"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadminpassword"